#!/usr/bin/env python3
"""Round 5 draft_02: provenance manifest — every output, the script that made it and what it was made from."""
from __future__ import annotations

import csv
import hashlib
import sys
from datetime import datetime, timezone
from pathlib import Path

S21 = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import draft02_map as M                                            # noqa: E402

D2 = S21 / "manuscript" / "v7.4" / "final_01" / "draft_02"
A = "analysis/v7.4_final01"

# path glob -> (built by, built from)
PROV = [
    ("figures/Figure6_parameter_to_exposure.*", A + "/fig06_parameter_to_exposure.py",
     "outputs/tables/upstream_parameter_fold_errors.csv, per_compound_metrics.csv, decomposition_routing.csv"),
    ("figures/Figure7_allpredicted_overview.*", A + "/build_draft02_si.py (copy + rename)",
     "manuscript/v7.4/figures_round4b/Figure6_allpredicted_overview.* (Round 4B, frozen)"),
    ("figures/Figure[1-5]_*.*", A + "/build_draft02_si.py (copy)",
     "manuscript/v7.4/figures_round4b/ (Round 4B, frozen)"),
    ("stats/figure6_parameter_to_exposure_spearman.csv", A + "/fig06_parameter_to_exposure.py",
     "recomputed with the same estimator, 10,000-resample bootstrap and seed 20260920 as the SI figures it replaces"),
    ("SI/figures/*", A + "/build_draft02_si.py (copy + renumber)",
     "manuscript/v7.4/SI/figures/ (Round 4C frozen set)"),
    ("SI/tables/*.md", A + "/build_draft02_si.py (copy)", "manuscript/v7.4/SI/tables/ (from manuscript/v4/SI)"),
    ("SI/src/body_si.md", A + "/build_draft02_si.py",
     "manuscript/v7.4/SI/src/body_si.md + the draft_02 remap in " + A + "/draft02_map.py"),
    ("SI/Supplementary_Information_v74b.*", A + "/build_draft02_si.py",
     "SI/src/body_si.md + SI/tables/*.md; .docx templated on manuscript/Supplementary Information v7.2.docx"),
    ("maintext/body_*.md", A + "/build_draft02_maintext.py, then " + A + "/fix_sources_round5c.py",
     "manuscript/v7.4/final_01/src/body_*.md; Round 5C terminology sweep and citation corrections applied"),
    ("maintext/v7.4_methods_results_draft02.md", A + "/build_draft02_maintext.py",
     "the draft_02 bodies with the frozen Round 4C captions resolved"),
    ("maintext/v7.4_methods_results_draft02.docx", A + "/build_draft02_maintext.py",
     "surgical edit of manuscript/v7.4/final_01/draft/v7.4_methods_results.docx (equations preserved)"),
    ("display/FIGURE_maintext_draft02.docx", A + "/build_draft02_display.py",
     "draft_02/figures/ + the approved captions; templated on final_01/sources/tables/TABLE_maintext.docx"),
    ("display/TABLE_maintext_draft02.docx", A + "/build_draft02_display.py",
     "tables copied from maintext/v7.4_methods_results_draft02.docx; same template"),
    ("qc/*", A + "/qc_draft02.py", "the draft_02 outputs themselves"),
    ("discussion/v7.4_discussion_round5c.docx", A + "/build_discussion_round5c.py",
     "surgical edit of draft_02/revised ACS JCIM v7.4.docx (Discussion only; EndNote fields deep-copied, "
     "references untouched); content per framing/round5c_framing_plan_v2_guardrailed.md"),
    ("discussion/v7.4_discussion_round5c_highlighted.docx", A + "/build_discussion_round5c.py",
     "word-level diff of the same build against draft_02/revised ACS JCIM v7.4.docx"),
    ("revised ACS JCIM v8.0.docx", "author-supplied (uploaded 2026-09-24 16:49)",
     "61 references, EndNote numbering of record; adopts the frozen Round 5C Discussion"),
    ("v8_framing/v8.0_abstract_conclusions.docx", A + "/build_abstract_conclusions_v8.py",
     "surgical edit of revised ACS JCIM v8.0.docx (Abstract paragraphs and Conclusions only); "
     "upstream-to-downstream narrative, numbers restricted to those v8.0's own Results reports"),
    ("v8_framing/v8.0_abstract_conclusions_highlighted.docx", A + "/build_abstract_conclusions_v8.py",
     "word-level diff of the same build against revised ACS JCIM v8.0.docx"),
    ("v8_framing/v8.0_abstract_conclusions*.pdf", "Microsoft Word export",
     "the corresponding .docx; verified by reading the PDF text, not by file size"),
    ("v8_framing/v8.0_framing_full.docx", A + "/build_figure1_intro_v8.py",
     "v8_framing/v8.0_abstract_conclusions.docx with the FIGURE 1 caption rewritten to the four panels "
     "and the two objectives restored in the paragraph that introduces the figure"),
    ("v8_framing/v8.0_framing_full_highlighted.docx", A + "/build_figure1_intro_v8.py",
     "word-level diff of the same build against v8.0_abstract_conclusions.docx"),
    ("v8_framing/v8.0_framing_full*.pdf", "Microsoft Word export",
     "the corresponding .docx; verified by reading the PDF text"),
    ("v8_framing/CHANGELOG_v8_abstract_conclusions.md", "hand-authored (not regenerated by any script)",
     "the v8.0 framing rewrite; verified by " + A + "/qc_abstract_conclusions_v8.py"),
    ("frozen/DISCUSSION_FROZEN_*.docx", "snapshot of discussion/v7.4_discussion_round5c.docx",
     "the DISCUSSION as frozen by the author on 2026-09-24; the framing build reads it as its baseline"),
    ("frozen/DISCUSSION_FROZEN_*.md", "snapshot of discussion/v7.4_discussion_round5c.md",
     "the same freeze, as markdown"),
    ("framing_draft/v7.4_framing_round5c.docx", A + "/build_framing_round5c.py",
     "surgical edit of discussion/v7.4_discussion_round5c.docx (Abstract, Introduction and Conclusions "
     "only; EndNote fields preserved by run-span substitution); content per "
     "framing/round5c_framing_plan_v2_guardrailed.md"),
    ("framing_draft/v7.4_framing_round5c_highlighted.docx", A + "/build_framing_round5c.py",
     "word-level diff of the same build against the frozen Discussion manuscript"),
    ("framing_draft/v7.4_framing_round5c.md", A + "/build_framing_round5c.py",
     "read back from framing_draft/v7.4_framing_round5c.docx; subscript and EndNote runs kept as markup"),
    ("framing_draft/v7.4_framing_round5c*.pdf", "Microsoft Word export",
     "the corresponding .docx in this folder"),
    ("framing_draft/CHANGELOG_framing.md", "hand-authored (not regenerated by any script)",
     "the Round 5C framing build; verified by " + A + "/qc_framing_round5c_final.py"),
    ("discussion/v7.4_discussion_round5c.md", A + "/build_discussion_round5c.py",
     "read back from discussion/v7.4_discussion_round5c.docx; subscript and EndNote runs preserved as markup"),
    ("**/*.pre_round5c", A + "/fix_sources_round5c.py (backup)",
     "the same file as it stood before the Round 5C terminology sweep and citation corrections"),
    ("**/*.pre_round5c.docx", A + "/fix_sources_round5c.py (backup)",
     "the same file as it stood before the Round 5C terminology sweep and citation corrections"),
    ("discussion/v7.4_discussion_round5c*.pdf", "Microsoft Word export",
     "the corresponding .docx in this folder"),
    ("revised ACS JCIM v7.4.docx", "author-supplied (uploaded 2026-09-24)",
     "the benchmark this round builds on: 216 paragraphs, 54 references, the reference numbering of record"),
    ("framing/*.md", "hand-authored (not regenerated by any script)",
     "Round 5C planning; round5c_framing_plan_v2_guardrailed.md is the binding plan"),
    ("round5_intro_discussion_reframing_planning_prompt.md", "author-supplied",
     "the binding planning specification for Round 5C"),
    ("discussion/CHANGELOG_discussion.md", "hand-authored (not regenerated by any script)",
     "the Round 5C build; verified by " + A + "/qc_discussion_round5c.py"),
    ("figures/Figure2_ml_train_test.*", A + "/fig02_train_test_3x3.py",
     "ML+training-raw/DL+ML_trainV4/pred_res/res_v1/res_{Fu,CL,VDss}.csv"),
    ("stats/figure2_train_test_metrics_draft02.csv", A + "/fig02_train_test_3x3.py",
     "the same prediction files; reproduces the frozen Round 4B Figure 2 statistics"),
    ("maintext/v7.4_methods_results_draft02_highlighted.docx", A + "/build_draft02_highlight.py",
     "word-level diff of final_01/draft/v7.4_methods_results.docx against the draft_02 edits"),
    ("README.md", "hand-written", "this round's change summary"),
]


def sha(p):
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for c in iter(lambda: fh.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


def main():
    (D2 / "qc").mkdir(parents=True, exist_ok=True)
    rows, seen = [], set()
    for pattern, by, frm in PROV:
        for p in sorted(D2.glob(pattern)):
            if not p.is_file() or p in seen:
                continue
            seen.add(p)
            rows.append(dict(path=str(p.relative_to(D2)), bytes=p.stat().st_size, sha256=sha(p),
                             built_by=by, built_from=frm,
                             mtime_utc=datetime.fromtimestamp(p.stat().st_mtime, timezone.utc)
                             .isoformat(timespec="seconds")))
    for p in sorted(D2.rglob("*")):
        if (p.is_file() and p not in seen and p.name != "MANIFEST.csv"
                and not p.name.startswith("~$")):      # Word lock files are not artifacts
            rows.append(dict(path=str(p.relative_to(D2)), bytes=p.stat().st_size, sha256=sha(p),
                             built_by="", built_from="",
                             mtime_utc=datetime.fromtimestamp(p.stat().st_mtime, timezone.utc)
                             .isoformat(timespec="seconds")))
    with (D2 / "MANIFEST.csv").open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    unattributed = [r["path"] for r in rows if not r["built_by"]]
    print("%d files, %.1f MB" % (len(rows), sum(r["bytes"] for r in rows) / 1e6))
    print("unattributed:", unattributed or "none — every file has a script and a source")


if __name__ == "__main__":
    main()
